# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, test-actions ]
  pull_request:
    branches: [ master, test-actions ]

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - env:
        BROOK_SG_KEY: ${{ secrets.BROOK_SG_KEY }}
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
      run: |
        BROOK_SG_KEY="$BROOK_SG_KEY" printenv BROOK_SG_KEY > ssh.key && chmod 400 ssh.key
        ssh root@brook-sg.elemti.com -i ssh.key "curl -s ipinfo.io/ip"
        ls
        exit 1

      # run: node -e 'console.log(require("fs").readFileSync("./ssh.key", "utf8"))'
      # run: ssh root@brook-sg.elemti.com -i ssh.key "curl -s ipinfo.io/ip"
      # run: exit 1
      
      # run: npm run build --if-present
      # run: npm test

